# End-to-end browser checks. Needs: pip install playwright && playwright install chromium,
# the app running on http://localhost:3100 (npm run build && npx next start -p 3100),
# and sample PDFs in /tmp/pdfs (python3 scripts/make-sample-pdfs.py /tmp/pdfs).
import re
from playwright.sync_api import sync_playwright
BASE="http://localhost:3100"
errs=[]; results=[]
def ok(name, cond, detail=""):
    results.append(("PASS" if cond else "FAIL", name, detail)); print(("PASS" if cond else "FAIL"), name, detail)
def money(txt):
    m=re.search(r"[−-]?₹[\d,]+(\.\d+)?", txt); 
    if not m: return None
    v=m.group(0); neg=v[0] in "−-"; return (-1 if neg else 1)*float(re.sub(r"[^\d.]","",v))
def stat(pg,label):
    card=pg.locator("div.rounded-lg.border", has=pg.locator(f"p.text-sm.text-muted-foreground:text-is('{label}')")).first
    return money(card.locator("p.money").inner_text())

with sync_playwright() as p:
    b=p.chromium.launch()
    ctx=b.new_context(viewport={"width":1366,"height":900}, accept_downloads=True)
    pg=ctx.new_page()
    pg.on("console", lambda m: errs.append((pg.url,m.text)) if m.type=="error" else None)
    pg.on("pageerror", lambda e: errs.append((pg.url,str(e))))
    pg.goto(f"{BASE}/settings"); pg.wait_for_timeout(600)
    # start from clean demo
    pg.get_by_role("button", name="Reset demo data").first.click(); pg.get_by_role("alertdialog").get_by_role("button", name="Reset demo data").click(); pg.wait_for_timeout(500)

    # ---------- Dashboard basics
    pg.goto(f"{BASE}/dashboard"); pg.wait_for_timeout(800)
    inc, sp, sv, su = stat(pg,"Incoming"), stat(pg,"Spending"), stat(pg,"Saved to goals"), stat(pg,"Surplus")
    ok("dashboard: incoming/spending/saved/surplus", (inc,sp,sv,su)==(35000,22800,8000,12200), (inc,sp,sv,su))
    ok("dashboard: 'Total Income' label gone", pg.get_by_text("Total Income").count()==0)
    ok("dashboard: other money in listed", pg.get_by_text("Paid back by friends").count()==1 and pg.get_by_text("Other money in (not income)").count()==1)
    svgt=pg.evaluate("Array.from(document.querySelectorAll('svg text')).map(t=>t.textContent)")
    ok("dashboard: chart axis titles + ₹ ticks", "Month" in svgt and "Amount (₹)" in svgt and any(t.startswith("₹") for t in svgt), svgt[:8])
    ok("dashboard: chart legend", pg.locator(".recharts-legend-item-text:text-is('Incoming')").count()==1)
    pg.screenshot(path="/tmp/shots/v3-dashboard.png", full_page=True)

    # ---------- Consistency: add expense → edit → delete → refresh
    pg.get_by_role("button", name="Add transaction").first.click(); pg.wait_for_timeout(300)
    dlg=pg.get_by_role("dialog")
    dlg.get_by_role("button", name="Save transaction").or_(dlg.get_by_role("button", name="Add transaction")).first.click()
    ok("tx form: validation shows errors", dlg.locator("#tx-amount-error").count()==1)
    dlg.locator("#tx-amount").fill("2000"); dlg.locator("#tx-date").fill("2026-09-20"); dlg.locator("#tx-description").fill("E2E Headphones")
    dlg.locator("#tx-category").click(); pg.get_by_role("option", name="Shopping").click()
    dlg.locator("#tx-importance").click(); pg.get_by_role("option", name="Discretionary").click()
    dlg.get_by_role("button", name=re.compile("^(Add|Save) transaction$")).last.click(); pg.wait_for_timeout(400)
    ok("add expense: spending +2000, surplus −2000", (stat(pg,"Spending"),stat(pg,"Surplus"))==(24800,10200), (stat(pg,"Spending"),stat(pg,"Surplus")))
    # edit via transactions page
    pg.goto(f"{BASE}/transactions"); pg.wait_for_timeout(600)
    pg.get_by_role("searchbox").fill("E2E"); pg.wait_for_timeout(200)
    pg.locator("table button", has_text="E2E Headphones").click(); pg.wait_for_timeout(300)
    pg.get_by_role("dialog").get_by_role("button", name="Edit").first.click(); pg.wait_for_timeout(300)
    pg.get_by_role("dialog").locator("#tx-amount").fill("500")
    pg.get_by_role("dialog").get_by_role("button", name="Save changes").click(); pg.wait_for_timeout(400)
    pg.keyboard.press("Escape")
    pg.goto(f"{BASE}/dashboard"); pg.wait_for_timeout(600)
    ok("edit to 500: spending 23300", stat(pg,"Spending")==23300, stat(pg,"Spending"))
    pg.goto(f"{BASE}/budget"); pg.wait_for_timeout(500)
    ok("budget page sees edit (shopping ₹1,849)", pg.get_by_text("₹1,849").count()>=1)
    pg.goto(f"{BASE}/transactions"); pg.wait_for_timeout(500)
    pg.get_by_role("searchbox").fill("E2E"); pg.locator("table button", has_text="E2E Headphones").click(); pg.wait_for_timeout(300)
    pg.get_by_role("dialog").get_by_role("button", name=re.compile("^Delete")).first.click(); pg.wait_for_timeout(200)
    pg.get_by_role("alertdialog").get_by_role("button", name=re.compile("Delete")).click(); pg.wait_for_timeout(400)
    pg.reload(); pg.wait_for_timeout(700)
    pg.goto(f"{BASE}/dashboard"); pg.wait_for_timeout(600)
    ok("delete + refresh: totals back", (stat(pg,"Spending"),stat(pg,"Surplus"))==(22800,12200))

    # ---------- Type change: expense → reimbursement changes totals
    pg.goto(f"{BASE}/transactions?review=1"); pg.wait_for_timeout(700)
    pg.locator("table button", has_text=re.compile("NEFT", re.I)).first.click(); pg.wait_for_timeout(300)
    dlg=pg.get_by_role("dialog")
    ok("type picker: money-in options only", dlg.get_by_role("radio", name=re.compile("^Expense")).count()==0 and dlg.get_by_role("radio", name=re.compile("^Income")).count()==1)
    dlg.get_by_role("radio", name=re.compile("^Income")).click()
    dlg.get_by_role("button", name=re.compile("Mark as reviewed|Save")).first.click(); pg.wait_for_timeout(400); pg.keyboard.press("Escape")
    pg.goto(f"{BASE}/dashboard"); pg.wait_for_timeout(600)
    ok("unknown ₹1,500 → income: incoming 36,500", stat(pg,"Incoming")==36500, stat(pg,"Incoming"))

    # ---------- Goals CRUD with refresh
    pg.goto(f"{BASE}/goals"); pg.wait_for_timeout(500)
    pg.get_by_role("button", name="New goal").click(); dlg=pg.get_by_role("dialog")
    dlg.get_by_role("button", name="Create goal").click()
    ok("goal form validation", dlg.locator("#goal-name-error").count()==1 and dlg.locator("#goal-targetAmount-error").count()==1)
    dlg.locator("#goal-name").fill("E2E Bike"); dlg.locator("#goal-targetAmount").fill("40000"); dlg.locator("#goal-deadline").fill("2027-06-30")
    ok("safety hint 1.5× = ₹60,000", dlg.get_by_text("Safety target: ₹60,000").count()==1)
    dlg.get_by_role("button", name="Create goal").click(); pg.wait_for_timeout(300); pg.reload(); pg.wait_for_timeout(700)
    ok("goal persists after refresh", pg.get_by_role("heading", name=re.compile("E2E Bike")).count()==1)
    pg.get_by_role("button", name="Edit E2E Bike").click(); dlg=pg.get_by_role("dialog")
    dlg.locator("#goal-targetAmount").fill("45000"); dlg.locator("#goal-safetyMultiplier").fill("2")
    dlg.get_by_role("button", name="Save changes").click(); pg.wait_for_timeout(300); pg.reload(); pg.wait_for_timeout(700)
    card=pg.locator("div.rounded-lg", has=pg.get_by_role("heading", name=re.compile("E2E Bike"))).first
    ok("goal edit persists: target 45k, safety 90k", card.get_by_text("₹90,000").count()>=1 and card.get_by_text("Target ₹45,000").count()==1)
    pg.get_by_role("button", name="Update savings").last.click(); dlg=pg.get_by_role("dialog")
    dlg.locator("#contrib-amount").fill("5000"); dlg.get_by_role("button", name="Record").click(); pg.wait_for_timeout(300)
    ok("goal progress updates", card.get_by_text("₹5,000").first.count()==1)
    pg.goto(f"{BASE}/tradeoffs"); pg.wait_for_timeout(500)
    ok("trade-offs sees new goal", pg.locator("#tradeoff-goal").count()==1)
    pg.goto(f"{BASE}/goals"); pg.wait_for_timeout(500)
    pg.get_by_role("button", name="Delete E2E Bike").click(); pg.get_by_role("alertdialog").get_by_role("button", name="Delete goal").click(); pg.wait_for_timeout(300)
    pg.reload(); pg.wait_for_timeout(600)
    ok("goal delete persists", pg.get_by_role("heading", name=re.compile("E2E Bike")).count()==0)

    # ---------- Trade-offs
    pg.goto(f"{BASE}/tradeoffs"); pg.wait_for_timeout(500)
    verdicts=[]
    for amt in ["₹1,000","₹6,000","₹20,000"]:
        pg.get_by_role("button", name=amt, exact=True).click(); pg.wait_for_timeout(150)
        verdicts.append(pg.get_by_role("status").first.inner_text().split("\n")[0])
    ok("trade-offs: 3 different results", len(set(verdicts))==3, verdicts)
    pg.locator("#purchase-what").fill("a new phone"); pg.locator("#purchase-amount").fill("0"); pg.wait_for_timeout(150)
    ok("trade-offs: zero rejected", pg.locator("#purchase-amount-error").count()==1)
    pg.locator("#purchase-amount").fill("-500"); ok("trade-offs: '-' can't be typed", pg.locator("#purchase-amount").input_value() in ("500","0",""), pg.locator("#purchase-amount").input_value())
    before=pg.locator("#purchase-amount").input_value()
    pg.locator("#purchase-amount").fill("abc")
    ok("trade-offs: pasted letters rejected, previous value kept", pg.locator("#purchase-amount").input_value()==before, (before, pg.locator("#purchase-amount").input_value()))
    pg.locator("#purchase-amount").fill(""); pg.locator("#purchase-amount").press_sequentially("1a2e3-4.5")
    ok("trade-offs: typed junk filtered (letters, e, -, . rejected in whole-rupee field)", pg.locator("#purchase-amount").input_value()=="12345", pg.locator("#purchase-amount").input_value())
    pg.locator("#purchase-amount").fill(""); pg.locator("#purchase-what").click()
    ok("trade-offs: empty → prompt, no result", pg.get_by_text("Enter a purchase amount").count()==1)
    pg.locator("#purchase-amount").fill("50000000"); pg.wait_for_timeout(150)
    ok("trade-offs: > ₹1 crore explained", "1 crore" in (pg.locator("#purchase-amount-error").inner_text() if pg.locator("#purchase-amount-error").count() else ""))
    pg.locator("#purchase-amount").fill("6000"); pg.wait_for_timeout(150)
    ok("trade-offs: description used", "Buying a new phone" in pg.get_by_role("status").first.inner_text())
    pg.screenshot(path="/tmp/shots/v3-tradeoffs.png", full_page=True)

    # ---------- Spending hierarchy
    pg.goto(f"{BASE}/spending"); pg.wait_for_timeout(700)
    pg.get_by_role("group", name="Filter by importance").get_by_role("button", name=re.compile("Discretionary")).click(); pg.wait_for_timeout(200)
    ok("spending: importance narrows categories", pg.get_by_role("heading", name=re.compile("discretionary spending for")).count()==1)
    btns=pg.locator("table button[aria-pressed]")
    first=btns.first.inner_text(); btns.first.click(); pg.wait_for_timeout(200)
    desc=pg.locator("text=/transactions? in Discretionary, /").first.inner_text()
    ok("spending: category narrows transactions", first in desc, desc)
    svgt=pg.evaluate("Array.from(document.querySelectorAll('svg text')).map(t=>t.textContent)")
    ok("spending: axis titles (day chart + category chart)", "Amount (₹)" in svgt and any(t.startswith("Day of") for t in svgt), [t for t in svgt if not t.startswith("₹") and not t.isdigit()])
    pg.screenshot(path="/tmp/shots/v3-spending.png", full_page=True)

    # ---------- Settings save/refresh
    pg.goto(f"{BASE}/settings"); pg.wait_for_timeout(500)
    pg.locator("#savingsPercent").fill("25")
    pg.locator("#savings").get_by_role("button", name="Save").click(); pg.wait_for_timeout(300)
    ok("settings: saved feedback", pg.locator("#savings").get_by_text("Saved").count()==1)
    pg.locator("#savingsPercent").fill("150"); pg.wait_for_timeout(100)
    ok("settings: invalid % blocked", pg.locator("#savingsPercent").input_value() in ("15","25"), pg.locator("#savingsPercent").input_value())
    pg.reload(); pg.wait_for_timeout(700)
    ok("settings: persists after refresh", pg.locator("#savingsPercent").input_value()=="25")
    pg.locator("#displayName").fill("Suppu Test"); pg.locator("#profile").get_by_role("button", name="Cancel").click()
    ok("settings: cancel reverts", pg.locator("#displayName").input_value()=="Aditi Kumar")
    ok("settings: no fake logout", pg.get_by_role("button", name=re.compile("log ?out|sign out", re.I)).count()==0)

    # ---------- Plan a day: savings allocation
    pg.goto(f"{BASE}/plan-a-day"); pg.wait_for_timeout(600)
    pg.get_by_role("radio", name="Add to savings").click(); pg.wait_for_timeout(300)
    btn=pg.get_by_role("button", name="Add to savings")
    ok("plan: 'Add to savings' shown for yesterday's unused 580", btn.count()==1 and pg.get_by_text("Move ₹580").count()==1)
    btn.click(); pg.wait_for_timeout(300); pg.reload(); pg.wait_for_timeout(600)
    ok("plan: savings move is recorded once", pg.get_by_text("was added to a goal").count()==1 and pg.get_by_role("button", name="Add to savings").count()==0)
    pg.screenshot(path="/tmp/shots/v3-plan.png", full_page=True)

    # ---------- Split & settle via UI (partial payment)
    pg.goto(f"{BASE}/owed"); pg.wait_for_timeout(500)
    pg.get_by_role("button", name="Record payment").first.click(); dlg=pg.get_by_role("dialog")
    dlg.locator("#pay-amount").fill("600"); dlg.get_by_role("button", name="Record payment").click(); pg.wait_for_timeout(300)
    ok("owed: partial payment → Part paid, ₹400 left", pg.get_by_text("Part paid").count()>=1 and pg.get_by_text("₹400 left").count()==1)

    # ---------- PDF import → review → correct → import → every page
    pg.goto(f"{BASE}/dashboard"); pg.wait_for_timeout(700)
    inc0, sp0 = stat(pg,"Incoming"), stat(pg,"Spending")
    pg.goto(f"{BASE}/data"); pg.wait_for_timeout(500)
    with pg.expect_file_chooser() as fc: pg.get_by_role("button", name="Upload PDF").click()
    fc.value.set_files("/tmp/pdfs/hdfc.pdf"); pg.wait_for_timeout(2500)
    ok("pdf: preview with 10 rows, reconciled", pg.get_by_role("button", name="Import 10 transactions").count()==1 and pg.get_by_text("Statement reconciles").count()==1)
    ok("pdf: preview has Dr/Cr + type/category/importance/status columns", all(pg.get_by_role("columnheader", name=n).count()==1 for n in ["Dr/Cr","Type","Category","Importance","Status"]))
    ok("pdf: card number masked in preview", pg.get_by_text(re.compile("ATW-XXXX1234")).count()>=1 and pg.get_by_text(re.compile("512967")).count()==0)
    pg.get_by_role("button", name="Edit SALARY SEP 2026 ACME TECH PVT LTD").click()
    pg.get_by_role("dialog").get_by_role("radio", name=re.compile("^Income")).click(); pg.get_by_role("button", name="Apply").click(); pg.wait_for_timeout(200)
    pg.get_by_role("button", name="Edit TRANSFER TO SAVINGS A/C XX4521").click()
    pg.get_by_role("dialog").get_by_role("radio", name=re.compile("^Own transfer")).click(); pg.get_by_role("button", name="Apply").click(); pg.wait_for_timeout(200)
    ok("pdf: corrected rows marked Corrected", pg.get_by_text("Corrected", exact=True).count()==2)
    pg.get_by_role("checkbox", name=re.compile("^Import INTEREST CREDIT")).uncheck()
    ok("pdf: exclusion updates count", pg.get_by_role("button", name="Import 9 transactions").count()==1)
    pg.screenshot(path="/tmp/shots/v4-pdf-preview.png", full_page=True)
    pg.get_by_role("button", name="Import 9 transactions").click(); pg.wait_for_timeout(500)
    ok("data: last import stats", pg.get_by_text("hdfc.pdf").count()>=1 and pg.locator("dt:text-is('Excluded by you') + dd").inner_text()=="1" and pg.get_by_text("Balances reconciled.").count()==1)
    pg.goto(f"{BASE}/dashboard"); pg.wait_for_timeout(700)
    inc1, sp1 = stat(pg,"Incoming"), stat(pg,"Spending")
    ok("import → Incoming +35,000 (salary corrected; refund/IMPS not income)", inc1-inc0==35000, (inc0,inc1))
    ok("import → Spending +16,902.50 (transfer excluded)", round(sp1-sp0,2)==16902.5, (sp0,sp1))
    ok("import → surplus consistent", stat(pg,"Surplus")==inc1-sp1)
    pg.goto(f"{BASE}/spending"); pg.wait_for_timeout(700)
    ok("spending page total matches dashboard", stat(pg,"Total spending")==sp1, stat(pg,"Total spending"))
    pg.goto(f"{BASE}/budget"); pg.wait_for_timeout(600)
    ok("budget: new unknown spending shows as unbudgeted", pg.locator("li", has_text="Unknown").first.count()==1)
    pg.goto(f"{BASE}/transactions?review=1"); pg.wait_for_timeout(700)
    ok("imported rows in review queue", pg.get_by_text(re.compile("UPI-SWIGGY")).count()>=1)
    # classify Swiggy → Food/Flexible, budget food +412
    pg.goto(f"{BASE}/budget"); pg.wait_for_timeout(500)
    food0 = money(pg.locator("div.space-y-2", has=pg.get_by_text("Food", exact=True)).first.locator("span.money").first.inner_text())
    pg.goto(f"{BASE}/transactions?review=1"); pg.wait_for_timeout(600)
    pg.locator("table button", has_text="UPI-SWIGGY").click(); pg.wait_for_timeout(300); dlg=pg.get_by_role("dialog")
    dlg.locator("#d-category").click(); pg.get_by_role("option", name="Food").click()
    dlg.locator("#d-importance").click(); pg.get_by_role("option", name="Flexible").click()
    dlg.get_by_role("button", name="Save and mark reviewed").click(); pg.wait_for_timeout(300); pg.keyboard.press("Escape")
    pg.goto(f"{BASE}/budget"); pg.wait_for_timeout(500)
    food1 = money(pg.locator("div.space-y-2", has=pg.get_by_text("Food", exact=True)).first.locator("span.money").first.inner_text())
    ok("classify imported Swiggy → Food budget +412", food1-food0==412, (food0, food1))
    # delete it, refresh, check
    pg.goto(f"{BASE}/transactions"); pg.wait_for_timeout(500)
    pg.get_by_role("searchbox").fill("SWIGGY-swiggy"); pg.locator("table button", has_text="UPI-SWIGGY").click(); pg.wait_for_timeout(300)
    pg.get_by_role("dialog").get_by_role("button", name=re.compile("^Delete")).first.click()
    pg.get_by_role("alertdialog").get_by_role("button", name=re.compile("Delete")).click(); pg.wait_for_timeout(300)
    pg.reload(); pg.wait_for_timeout(700)
    pg.goto(f"{BASE}/budget"); pg.wait_for_timeout(500)
    food2 = money(pg.locator("div.space-y-2", has=pg.get_by_text("Food", exact=True)).first.locator("span.money").first.inner_text())
    ok("delete + refresh → Food back", food2==food0, food2)
    pg.goto(f"{BASE}/dashboard"); pg.wait_for_timeout(600)
    ok("delete + refresh → dashboard spending −412", round(sp1-stat(pg,"Spending"),2)==412)
    # goals/trade-offs use the post-import surplus
    sur = stat(pg,"Surplus")
    pg.goto(f"{BASE}/tradeoffs"); pg.wait_for_timeout(500)
    ok("trade-offs uses the post-import surplus", pg.get_by_text(re.compile(r"surplus " + re.escape(f"₹{int(sur):,}".replace(",", ",")) )).count()>=1 or pg.get_by_text(f"₹{sur:,.2f}".rstrip("0").rstrip(".")).count()>=1, sur)
    # re-upload: only the excluded interest row is new
    pg.goto(f"{BASE}/data"); pg.wait_for_timeout(500)
    with pg.expect_file_chooser() as fc: pg.get_by_role("button", name="Upload PDF").click()
    fc.value.set_files("/tmp/pdfs/hdfc.pdf"); pg.wait_for_timeout(2000)
    ok("pdf: re-upload → only the excluded row + deleted Swiggy are new", pg.get_by_role("button", name="Import 2 transactions").count()==1)
    pg.get_by_role("button", name="Cancel").click()
    with pg.expect_file_chooser() as fc: pg.get_by_role("button", name="Upload PDF").click()
    fc.value.set_files("/tmp/pdfs/bad-row.pdf"); pg.wait_for_timeout(2000)
    ok("pdf: bad row → 'doesn't reconcile' warning + rejected row listed", pg.get_by_text("Statement doesn't reconcile").count()==1 and pg.get_by_text(re.compile("rejected and won")).count()==1)
    pg.get_by_role("button", name="Cancel").click()
    with pg.expect_file_chooser() as fc: pg.get_by_role("button", name="Upload PDF").click()
    fc.value.set_files("/tmp/pdfs/hdfc-locked.pdf"); pg.wait_for_timeout(1500)
    ok("pdf: password prompt", pg.locator("#pdf-password").count()==1)
    pg.locator("#pdf-password").fill("wrong"); pg.get_by_role("button", name="Open PDF").click(); pg.wait_for_timeout(1500)
    ok("pdf: wrong password message", pg.get_by_text("That password didn't open the PDF.").count()==1)
    pg.locator("#pdf-password").fill("DDMM1990"); pg.get_by_role("button", name="Open PDF").click(); pg.wait_for_timeout(2000)
    ok("pdf: unlocked → recognised as same statement (2 new)", pg.get_by_role("button", name="Import 2 transactions").count()==1)
    pg.get_by_role("button", name="Cancel").click()
    for f,msg in [("letter.pdf","Could not confidently detect"),("scanned.pdf","no selectable text")]:
        with pg.expect_file_chooser() as fc: pg.get_by_role("button", name="Upload PDF").click()
        fc.value.set_files(f"/tmp/pdfs/{f}"); pg.wait_for_timeout(1500)
        ok(f"pdf: {f} refused honestly", pg.get_by_text(re.compile(msg)).count()==1)
        pg.get_by_role("button", name="Remove file").click()
    with pg.expect_file_chooser() as fc: pg.get_by_role("button", name="Upload CSV").click()
    fc.value.set_files("/tmp/pdfs/sbi.pdf"); pg.wait_for_timeout(300)
    ok("wrong button → clear error", pg.get_by_text(re.compile("is a PDF file, not CSV")).count()==1)

    # ---------- Spending periods
    pg.goto(f"{BASE}/spending"); pg.wait_for_timeout(600)
    pg.get_by_role("radio", name="Week", exact=True).click(); pg.wait_for_timeout(200)
    ok("spending: week comparison shows ranges", pg.get_by_text(re.compile("This week so far|Period ending")).count()==1)
    pg.get_by_role("radio", name="Weekly", exact=True).click(); pg.wait_for_timeout(300)
    svgt=pg.evaluate("Array.from(document.querySelectorAll('svg text')).map(t=>t.textContent)")
    ok("spending: weekly chart labelled", any(t.startswith("Week (days of") for t in svgt), [t for t in svgt if "Week" in t])
    pg.goto(f"{BASE}/budget"); pg.wait_for_timeout(500)
    ok("budget: budget-vs-actual chart with legend", pg.locator(".recharts-legend-item-text:text-is('Budget')").count()==1 and pg.locator(".recharts-legend-item-text:text-is('Actual')").count()==1)
    pg.goto(f"{BASE}/plan"); pg.wait_for_timeout(700)
    ok("/plan redirects to /plan-a-day", pg.url.endswith("/plan-a-day"))

    # ---------- Responsive
    for vw,vh,tag in [(390,844,"m"),(820,1180,"t"),(1280,800,"l")]:
        page=b.new_context(viewport={"width":vw,"height":vh}).new_page()
        for name in ["dashboard","transactions","spending","plan-a-day","tradeoffs","data","goals","owed","budget","settings"]:
            page.goto(f"{BASE}/{name}"); page.wait_for_timeout(500)
            w=page.evaluate("Math.max(document.documentElement.scrollWidth, document.querySelector('main')?.scrollWidth||0)")
            if w>vw+1: ok(f"{tag} {name}: no horizontal overflow", False, w)
            if name in ("dashboard","spending","data") : page.screenshot(path=f"/tmp/shots/v3-{tag}-{name}.png", full_page=True)
        page.close()
    b.close()
print("\nconsole errors:", errs[:8])
print("FAILED:", [r[1] for r in results if r[0]=="FAIL"])
print(f"{sum(r[0]=='PASS' for r in results)}/{len(results)} passed")
